/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f767xx.h"


void delayMs(uint32_t ms);


int main(void)
{
    /* Loop forever */
    RCC->AHB1ENR |= 0x2;
    GPIOB->MODER &= ~(0x3 << 14);
    GPIOB->MODER|= (1<<14);

	for(;;)
	{
	    GPIOB->ODR |= (1 << 7);
	    delayMs(500);
	    GPIOB->ODR &= ~(1 << 7);
	    delayMs(500);
	}
}

void delayMs(uint32_t ms)
{
    for (; ms > 0; ms--)
    {
        for (int i=0; i < 3195; i++);
    }
}
